version: 2.1

parameters:
  remote-trigger:
    type: boolean
    default: false
  project:
    type: string
    default: ""
  release-tag:
    type: string
    default: ""
  build-dir:
    type: string
    default: ""

commands:
  setup-git:
    steps:
      - run:
          name: Setup git
          command: |
            git config --global --remove-section "url.ssh://git@github.com"
            git config --global url."https://${GITHUB_TOKEN}:@github.com/".insteadOf "https://github.com/"
            git remote set-url origin "https://${GITHUB_TOKEN}:@github.com/banzaicloud/one-eye-docs"
            git config --global user.email "circleci@circleci.com"
            git config --global user.name "CircleCI"

jobs:
  generate-docs:
    docker:
      - image: cimg/go:1.13
    resource_class: small
    steps:
      - checkout
      - setup-git
      - run:
          name: Update CLI docs
          command: |
            scripts/update-generated-docs.sh \
              "<<pipeline.parameters.project>>" \
              "<<pipeline.parameters.release-tag>>" \
              "<<pipeline.parameters.build-dir>>"

  trigger-submodule-update:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: Trigger
          command: scripts/trigger-submodule-update.sh

workflows:
  cli-docgen:
    when: << pipeline.parameters.project >>
    jobs:
      - generate-docs:
          context: Default

  submodule-update-on-main-site:
    unless: << pipeline.parameters.remote-trigger >>
    jobs:
      - trigger-submodule-update:
          filters:
            branches:
              only: master
